Проектная работа №13. Первый заход на ревью.
YuliaPotapova/product_13.github.io pull request #1
Opened 2020-05-20 14:53 UTC by YuliaPotapova

В рамках данного проекта:
- в файл конфигурации линтера .eslintrc добавлено исключение для имён переменных с подчёркиванием (_id);
- Node.js приложение подключается к серверу баз данных Mongo;
- создана новая база данных;
- описаны схемы и созданы модели документов БД;
- созданы контроллеры и роуты;
- поля схем валидируются средствами mongoose и дополнительно установленного npm-модуля validator;
- выполнено дополнительное задание.

2020-05-21 07:48 UTC, aarefiev requested changes
Очень хорошая работа. Выполнено доп задание :+1: .

Очень хорошее описание проекта. Проект хорошо структурирован, элементы сгруппированы в группы по принадлежности (роуты, контроллеры, модели). Для статической проверки синтаксиса подключен линтер `eslint`, устанавливающий соответствие стайлгайду _Airbnb_. Линтер завершается ошибкой. Отдельного конфигурационного файла со всеми настройками для работы сервера не обнаружено. Схемы моделей настроены корректно, согласно заданию. Схемы роутов настроены корректно, согласно заданию, но есть ошибки в кодах ответов при нештаных ситуациях. Централизованная обработка несуществующего роута есть, работает. Раздача статики удалена. Сервер запускается в режим хот-релоада и без, ошибки в консоли не возникают. Временные файлы игнорируются.

Краткий список ошибок и улучшений представлен ниже, расширенные комментарии непосредственно в коде.

**Нужно исправить:**
1. Ошибки линтинга.
2. Не работает обновление профиля.
3. При установке лайка на карточку, которая не существует в базе, возвращается 200.
4. При удалении лайка с карточки, которая не существует в базе, возвращается 200.

**Можно лучше:**
1. Вынести настройки в отдельный конфигурационный файл.
2. Вынести подключение роутов в отдельный файл.
3. Валидировать данные до передачи их в контроллер.
4. Использовать встроенные хелперы `mongoose` для обработки несуществующей записи.
5. `useUnifiedTopology`.
6. Доработать README.md.

2020-05-21 07:48 UTC, aarefiev commented on app.js
> +const { PORT = 3000 } = process.env;
Можно лучше: вынести настройки в отдельный конфигурационный файл.
Если оставить определение значений в коде, то возникает несколько очевидных проблем:
- изменение какой-то настройки требует изменений всех файлов, где она используется,
- нельзя использовать отдельные настройки для разработки и продакшена

Лучше создать отдельный файл (например, `config.js`) и в нём уже заполнять те настройки, которые будут использоваться в проекте (например, секретный ключ, порт сервера или адрес для подключения к базе данных). Далее этот файл подключать в тех файлах, где необходимо получить значения. Пример файла:
```js
// config.js
module.exports.PORT = process.env.PORT || 3000;
module.exports.DATABASE_URL = 'mongodb://localhost:27017/mestodb';
```

2020-05-21 07:48 UTC, aarefiev commented on app.js
> +mongoose.connect('mongodb://localhost:27017/mestodb', {
Можно лучше: вынести настройки в отдельный конфигурационный файл.
Адрес для подключения к базе данных.

2020-05-21 07:48 UTC, aarefiev commented on app.js
> +app.use((req, res) => res.status(404).json({ message: 'Запрашиваемый ресурс не найден' }));
Можно лучше: вынести подключение роутов в отдельный файл.
Уровень `app.js` является точкой входа в проект. Обычно понимание проще, когда мы оперируем абстракциями, а не конкретной реализацией. Конечно в текущем виде роуты для `/users`, `/cards`, обработка несуществующего роута уже абстрагирована, но можно добавить ещё одну, которая объединяет их общим - всё это роуты приложения. К тому же внедрение этой абстракции позволит оставить код, назначающий роуты в одном файле, что сделает код более читабельным.

Например, можно создать `routes/index.js` файл, в который перенести подключение всех роутов + обработку несуществующего роута. А в `app.js` оставить лишь подключение:
```js
const routes = require('./routes');

app.use(routes);
```

2020-05-21 07:48 UTC, aarefiev commented on controllers/cards.js
> +        res.status(400).send({ message: 'Некорректное название карточки или неверная ссылка на ресурс' });
Можно лучше: валидировать данные до передачи их в контроллер.
По идее контроллер уже работает с корректными данными. И все ошибки, которые возникают уже можно считать ошибками на сервере. Поэтому можно спокойно возвращать 500.
Валидацию можно провести до выполнения контроллера, например, на уровне роутинга.

2020-05-21 07:48 UTC, aarefiev commented on controllers/cards.js
> +        res.status(404).send({ message: 'Нет карточки с таким id' });
Можно лучше: использовать встроенные хелперы `mongoose` для обработки несуществующей записи.
В `mongoose` по-умолчанию методы, которые делают выборку значений из базы данных по какому-то
условию, возвращают `null` в случае отсутствия записи в базе данных. Для того, чтобы отловить эту ситуацию есть хелпер [`.orFail()`](https://mongoosejs.com/docs/api.html#query_Query-orFail).

Хелпер принимает функцию, которая выполняет _reject_ промиса. Если функция будет возвращать какое-то значение, оно будет передано в `.catch()` блок, если нет, то будет отправлено значение по-умолчанию.

Но это не всё. Ещё нужно корректно прокинуть код ошибки. Так как внутри `orFail()` хелпера можно передать любое значение, то я рекомендую создать отдельный модуль для ошибки. Модуль будет содержать класс, который наследует класс `Error` добавляя туда свойство, в котором будет определен HTTP код ошибки. Например для 404 он будет выглядеть так:
```js
// errors/notFoundError.js
class NotFoundError extends Error {
  constructor(message) {
    super(message);
    this.statusCode = 404;
  }
}

module.exports = NotFoundError;
```

Далее отправка ошибки в `orFail()` сводится к следующему:
```js
.orFail(() => new NotFoundError('Карточка не найдена'))
```

А передача кода уходит в `.catch()` блок:
```js
.catch((err) => {
  const statusCode = err.statusCode || 500;
  const message = statusCode === 500 ? 'Произошла ошибка' : err.message;
  res.status(statusCode).send({ message });
});
```

2020-05-21 07:48 UTC, aarefiev commented on controllers/users.js
> +        res.status(404).send({ message: 'Нет пользователя с таким id' });
Можно лучше: использовать встроенные хелперы `mongoose` для обработки несуществующей записи.

2020-05-21 07:48 UTC, aarefiev commented on controllers/users.js
> +        res.status(400).send({ message: 'Данные пользователя введены некорректно' });
Можно лучше: валидировать данные до передачи их в контроллер.

2020-05-21 07:48 UTC, aarefiev commented on controllers/users.js
> +        res.status(400).send({ message: 'Неверная ссылка на ресурс' });
Можно лучше: валидировать данные до передачи их в контроллер.

2020-05-21 07:48 UTC, aarefiev commented on controllers/users.js
> +        res.status(400).send({ message: err.message });
Можно лучше: валидировать данные до передачи их в контроллер.

2020-05-21 07:48 UTC, aarefiev commented on app.js
> +﻿const express = require('express');
Нужно исправить: ошибки линтинга.
```bash
$ npx eslint --ext .js .

/home/jmi/work/ya-reviews/product_13.github.io/app.js
  1:1  error  Unexpected Unicode BOM (Byte Order Mark)  unicode-bom

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

Ожидаемый результат - ошибок маркированных **error** нет (**warning** допускается).

2020-05-21 07:48 UTC, aarefiev commented on app.js
> +  useFindAndModify: false,
Можно лучше: `useUnifiedTopology`.
> (node:27356) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

2020-05-21 07:48 UTC, aarefiev commented on controllers/users.js
> +    req.params._id,
Нужно исправить: не работает обновление профиля.
Идентификатор пользователя определен, он не передается в парамтерах для запроса:
https://github.com/YuliaPotapova/product_13.github.io/blob/1eddd0a4e3678d245d339436fe1b3925ff6bff5b/app.js#L19-L21

2020-05-21 07:48 UTC, aarefiev commented on controllers/users.js
> +    req.params._id,
Нужно исправить: не работает обновление профиля.

2020-05-21 07:48 UTC, aarefiev commented on controllers/cards.js
> +    .then((card) => res.send({ data: card }))
Нужно исправить: при установке лайка на карточку, которая не существует в базе, возвращается 200.
Запрос `PUT /cards/5ec62deaf5b4cb7ea6adfdd8/likes`.
Ответ с кодом 200:
```json
{
    "data": null
}
```
Ожидаемый результат - будет возвращен ответ с кодом 404.

2020-05-21 07:48 UTC, aarefiev commented on controllers/cards.js
> +    .then((card) => res.send({ data: card }))
Нужно исправить: при удалении лайка с карточки, которая не существует в базе, возвращается 200.
Аналогично комментарию выше.

2020-05-21 07:48 UTC, aarefiev commented on README.md
> +* поля схем валидируются средствами mongoose и дополнительно установленного npm-модуля validator.
Можно лучше: доработать README.md.
Нужно указать в описании:
- инструкцию о том как развернуть проект локально

Дополнительно скину ресурсы, которые помогут его улучшить:
- статья "[Как написать хороший README?](https://medium.com/astrolabe/%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B8%D0%B9-readme-159f88076b26)".
- примеры шаблонов для README:
  - https://gist.github.com/PurpleBooth/109311bb0361f32d87a2,
  - https://gist.github.com/fvcproductions/1bfc2d4aecb01a834b46

2020-05-21 21:01 UTC, YuliaPotapova commented
Здравствуйте, Артём!
Спасибо за подробное ревью! Устранила все замечания, кроме пункта валидации данных до передачи их в контроллер, не совсем поняла, что Вы имели в виду. Сейчас валидация организована на уровне схемы, поэтому данные валидируются при вызове метода модели. А чтобы вынести её на уровень роутинга нужно написать функцию проверки всех условий и вызывать её между URL и контроллером в методе роута?

2020-05-21 21:50 UTC, YuliaPotapova commented
Поспешила отправить, не протестировав полноценно... Почему-то проброс ошибки через .orFail в .catch для лайков работает, а для удаления карточки - нет, хотя в коде конструкции абсолютно идентичные :'(  Смотрите тогда коммит "Устранены замечания с пометкой 'нужно исправить'", там всё работало.

2020-05-22 15:41 UTC, aarefiev requested changes
> Почему-то проброс ошибки через .orFail в .catch для лайков работает, а для удаления карточки - нет, хотя в коде конструкции абсолютно идентичные :'(

Забыл об этом упомянуть. Хорошо, что заметили. Это связано с особенностью реализации метода. Я добавил комментарий с ошибкой и описал как исправить.

В остальном всё отлично.

**Нужно исправить:** при удалении карточки, которая не существует в базе, возвращается 200.

**Можно лучше:**
1. Не использовать файл конфигурации в качестве прослойки для экспортирования модулей.
2. Точку входа в группу модулей именовать `index.js`.
3. Унифицировать ответ для ошибок на сервере.

2020-05-22 15:41 UTC, aarefiev commented on config.js
> +module.exports.routCards = require('./routes/cards.js');
Можно лучше: не использовать файл конфигурации в качестве прослойки для экспортирования модулей.
Конфигурационный файл нужен, чтобы определить базовые значения. Например, в случае с портом он может быть как передан при запуске сервера (через Environment Variables), так и использовано предустановленное значение. 
Модули по своей сути всегда статичны.

2020-05-22 15:41 UTC, aarefiev commented on app.js
> +const routes = require('./routes/routes');
Можно лучше: точку входа в группу модулей именовать `index.js`.
`index.js` является базовым файлом, который будет подключен по-умолчанию, если будет произведено подключение модуля. Например, если переименовать, то можно подключить роуты вот так:
```suggestion
const routes = require('./routes');
```

Как минимум стало короче.

2020-05-22 15:41 UTC, aarefiev commented on controllers/users.js
> +    .catch((err) => res.status(500).send({ message: err.message }));
Можно лучше: унифицировать ответ для ошибок на сервере.
В большинстве случаев клиент не в состоянии поправить ошибку на сервере. Поэтому детали ошибки ему нет смысла отправлять. Обычно детали ошибки логируются на сервере в файл/консоль/менеджер ошибок (типа Sentry, Honeybadger).

Но ответ нужно какой-то отдавать поэтому рекомендую оставить какой-то общий текст. Например, можно отправлять сообщение типа `Произошла ошибка`.

2020-05-22 15:41 UTC, aarefiev commented on controllers/users.js
> +    .catch((err) => res.status(err.statusCode || 500).send({ message: err.message }));
Можно лучше: унифицировать ответ для ошибок на сервере.
Здесь стоит учесть, что в случае если будет брошено исключение о том, что запись отсутвует, нужно вернуть текст, который указан в экземпляре ошибки. Т.е. достаточно проверить значение `statusCode`.

2020-05-22 15:41 UTC, aarefiev commented on controllers/users.js
> +        res.status(500).send({ message: err.message });
Можно лучше: унифицировать ответ для ошибок на сервере.

2020-05-22 15:41 UTC, aarefiev commented on controllers/users.js
> +        res.status(500).send({ message: err.message });
Можно лучше: унифицировать ответ для ошибок на сервере.

2020-05-22 15:41 UTC, aarefiev commented on controllers/users.js
> +        res.status(500).send({ message: err.message });
Можно лучше: унифицировать ответ для ошибок на сервере.

2020-05-22 15:41 UTC, aarefiev commented on controllers/cards.js
> +    .catch((err) => res.status(500).send({ message: err.message }));
Можно лучше: унифицировать ответ для ошибок на сервере.

2020-05-22 15:41 UTC, aarefiev commented on controllers/cards.js
> +        res.status(500).send({ message: err.message });
Можно лучше: унифицировать ответ для ошибок на сервере.

2020-05-22 15:41 UTC, aarefiev commented on controllers/cards.js
> +    .catch((err) => res.status(err.statusCode || 500).send({ message: err.message }));
Можно лучше: унифицировать ответ для ошибок на сервере.
Здесь стоит учесть, что в случае если будет брошено исключение о том, что запись отсутвует, нужно вернуть текст, который указан в экземпляре ошибки. Т.е. достаточно проверить значение `statusCode`.

2020-05-22 15:41 UTC, aarefiev commented on controllers/cards.js
> +    .catch((err) => res.status(err.statusCode || 500).send({ message: err.message }));
Можно лучше: унифицировать ответ для ошибок на сервере.
Здесь стоит учесть, что в случае если будет брошено исключение о том, что запись отсутвует, нужно вернуть текст, который указан в экземпляре ошибки. Т.е. достаточно проверить значение `statusCode`.

2020-05-22 15:41 UTC, aarefiev commented on controllers/cards.js
> +    .catch((err) => res.status(err.statusCode || 500).send({ message: err.message }));
Можно лучше: унифицировать ответ для ошибок на сервере.
Здесь стоит учесть, что в случае если будет брошено исключение о том, что запись отсутвует, нужно вернуть текст, который указан в экземпляре ошибки. Т.е. достаточно проверить значение `statusCode`.

2020-05-22 15:41 UTC, aarefiev commented on controllers/cards.js
> +    .orFail(() => new NotFoundError('Нет карточки с таким id'))
Нужно исправить: при удалении карточки, которая не существует в базе, возвращается 200.
Метод `.orFail()` не работает с методом `.findByIdAndRemove()`, но работает с методом `.findByIdAndDelete()`. Эти два метода по сути похожи, но немного различаются. Детали можно прочитать в документации.

Здесь я рекомендую разделить удаление на два запроса. Первый запрос на получение карточки, те `.findById()` и второй на удаление - [`.remove()`](https://mongoosejs.com/docs/api/model.html#model_Model.remove).
В следующей практике это всё равно потребуется.

2020-05-23 14:36 UTC, aarefiev approved these changes
Отлично. Ошибки исправлены, новых не обнаружено.
Работа принимается :rocket:.

**Можно лучше:** использование `async/await` выглядит лишним.

2020-05-23 14:36 UTC, aarefiev commented on controllers/cards.js
> +    })
Можно лучше: использование `async/await` выглядит лишним.
Эта связка позволяет писать асинхронный код в синхронном виде. Но, когда большая часть кода написана через _chainable_ функции, то выглядит немного не к месту. Рекомендую продолжить с промисами:
```suggestion
    .then((card) => Card.deleteOne(card).then(() => res.send({ data: card })))
```

2020-05-23 18:28 UTC, merged